// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV5L960aONby7cvY-cQ7DTe8TSrf2j9rw',
    appId: '1:339288104139:web:ee4c3d448982a858d74f4e',
    messagingSenderId: '339288104139',
    projectId: 'auth-testing-farhan',
    authDomain: 'auth-testing-farhan.firebaseapp.com',
    storageBucket: 'auth-testing-farhan.firebasestorage.app',
    measurementId: 'G-89WCCCH4B0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbyuzQi4fHhfVVL3jReiV44k3Qeul-kQg',
    appId: '1:339288104139:android:71ae62acb3074c6ed74f4e',
    messagingSenderId: '339288104139',
    projectId: 'auth-testing-farhan',
    storageBucket: 'auth-testing-farhan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFwfkYSy3ZgJcINUowmD_zPTqSGjdkqNU',
    appId: '1:339288104139:ios:40a1663826420b66d74f4e',
    messagingSenderId: '339288104139',
    projectId: 'auth-testing-farhan',
    storageBucket: 'auth-testing-farhan.firebasestorage.app',
    iosClientId: '339288104139-sof0gvkeoueke1rmdlktbuoc89ia5hho.apps.googleusercontent.com',
    iosBundleId: 'com.example.watchStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFwfkYSy3ZgJcINUowmD_zPTqSGjdkqNU',
    appId: '1:339288104139:ios:40a1663826420b66d74f4e',
    messagingSenderId: '339288104139',
    projectId: 'auth-testing-farhan',
    storageBucket: 'auth-testing-farhan.firebasestorage.app',
    iosClientId: '339288104139-sof0gvkeoueke1rmdlktbuoc89ia5hho.apps.googleusercontent.com',
    iosBundleId: 'com.example.watchStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV5L960aONby7cvY-cQ7DTe8TSrf2j9rw',
    appId: '1:339288104139:web:dcdfd4ada42ee0eed74f4e',
    messagingSenderId: '339288104139',
    projectId: 'auth-testing-farhan',
    authDomain: 'auth-testing-farhan.firebaseapp.com',
    storageBucket: 'auth-testing-farhan.firebasestorage.app',
    measurementId: 'G-K75JRVP149',
  );
}
